<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>GoldBar</AssemblyName>
    <RootNamespace>GoldBar.Windows</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Version>1.4.1</Version>
    <FileVersion>1.4.1.0</FileVersion>
    <AssemblyVersion>1.4.1.0</AssemblyVersion>
    <PublishReadyToRun>true</PublishReadyToRun>
    <TieredCompilation>true</TieredCompilation>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\GoldBar.Core\GoldBar.Core.csproj" />
    <PackageReference Include="System.IO.Ports" Version="8.0.0" />
  </ItemGroup>
</Project>
